# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "email": "teste@email.com" ,
   "password": "bruna6"
}

###

@id = {{signup.response.body.newUser.id}}

PUT http://localhost:3003/user/edit/{{id}}
Content-Type: application/json

{
   "name": "Harry Osbourne" 
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "teste@email.com" ,
   "password": "bruna6"
}

###
GET http://localhost:3003/user/profile
{
Authorization:"fd0a6c75-3d6e-429c-9c2e-da832edb4920"}